### ISSUE TITLE
Comments on bot retweets trigger sauce lookups

### ISSUE THREAD

**Issue by rainyroads** [rainyroads/twitter-saucenao#5] opened 2020-06-25 02:50 UTC
Example:
https://twitter.com/yoitstinyman/status/1275971460335534080

When someone comments on a retweet by the bot account, it ends up being parsed as someone mentioning the bot for a sauce lookup.

The reason why is because @saucenao is technically mentioned in the Tweet text,
![image](https://user-images.githubusercontent.com/7929996/85647613-de44de80-b66c-11ea-8d11-903353de190b.png)

Will need to look into this and see if there's some kind of flag or anything the API sends to easily differentiate actual mentions from comments on retweets. (If not, we'll need to make up our own solution.)

**Comment by FujiMakoto** [comment] 2020-06-27 21:52
Yeah, Twitter doesn't seem to provide us with anything useful in determining this.

![image](https://user-images.githubusercontent.com/7929996/85932894-97d6c600-b89e-11ea-9f21-cde08ea036b4.png)

There's no flag that says "this comment was in response to a retweet," it literally just appears exactly the same as if someone had mentioned the bot.

The only way I can see to mitigate this is to monitor the bots account home timeline, find anything we retweet, and add that to an internal blacklist (meaning, we won't be able to respond to any mentions in that post even if it is a proper bot trigger).

Which, is not ideal, but it would be preferably to the current situation.

**Comment by Satoshiii-DCS** [comment] 2020-07-20 02:47
I'm not too sure about a permanent fix, but the bot might be able to filter tweets that contains media and tweets that have none.

Go to [Twitter API docs](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object) then head over to Media Objects for complete details.

> The entities section will contain a media array containing a single media object if any media object has been ‘attached’ to the Tweet. If no native media has been attached, there will be no media array in the entities. For the following reasons the extended_entities section should be used to process Tweet native media:
> + Media type will always indicate ‘photo’ even in cases of a video and GIF being attached to Tweet.
> + Even though up to four photos can be attached, only the first one will be listed in the entities section.
> 
> The has:media Operator will match if this array is populated.

SauceBot won't be able to differentiate comments from mentions since a comment automatically includes a mention to notify the people involved in a Twitter thread that there is a new comment. However, using the Media Objects entity, it might be possible for a filter to be created in order for the bot to differentiate between comments that usually have no media and mentions.

Note: Comments that include a GIF might still be parsed as a media though.

**Comment by FujiMakoto** [comment] 2020-07-20 02:58
@Satoshiii-DCS I think I see what you are saying, though the problem lies in the different ways the bot is designed to operate.

From some of the refactored code documentation I am working on,
```python
    def get_closest_media(self, tweet) -> dict:
        """
        Find the closet media post associated with this tweet.
        This could be this tweet itself if someone has mentioned us with an upload.
        This could be a comment where the direct parent is the media we need to look up.
        This could also be a comment further down a chain of comments on a parent post, in which case we will need to
        traverse several tweets to find something to look up.
        Args:
            tweet: tweepy.models.Status object. Not type hinted because type hinting doesn't work with tweepy.

        Returns:
            Tweet
        """
```
So the problem is the bot is designed to "look up the chain" when mentioned to find the closest media item whenever its mentioned, and since commenting on a retweet always mentions the bots, it makes it look like someone is requesting the sauce of the retweet any time they comment on it.

**Comment by Satoshiii-DCS** [comment] 2020-07-20 03:23
Do you have a Discord server for saucebot? I might be able to discuss things better there.

**Comment by FujiMakoto** [comment] 2020-07-20 03:43
> Do you have a Discord server for saucebot? I might be able to discuss things better there.

I do! You can join here:
https://discord.gg/p2VQTFP

**Comment by FujiMakoto** [comment] 2021-05-12 22:55
Twitter is rolling out a new API and I have no idea if there's going to be any changes that will help address this or not.

If not, I'm likely just going to consider this an unfixable issue and close this. But we need to see where the new API takes us first.

**Closed** 2024-06-24 05:08 UTC
Labels: bug, help wanted
